"""Branch Cut visualisation — Ln(z) Riemann surface with spiral height and branch cut along negative real axis."""

from app.animation.base import BaseManimTemplate


class BranchCutTemplate(BaseManimTemplate):
    template_name = "BranchCut"
    concept_ids = ["complex-3.1"]
    scene_class_name = "BranchCutScene"

    def validate(self, params: dict) -> bool:
        required = {"function"}
        if not required.issubset(params):
            return False
        if not params.get("function"):
            return False
        return True

    def build_scene_code(self, params: dict) -> str:
        import json
        func_val = json.dumps(params.get("function", "Ln(z)"))
        return f'''"""Branch Cut animation — auto-generated by AnimationGenerator."""
import numpy as np
from manim import *

class {self.scene_class_name}(ThreeDScene):
    def construct(self):
        func_str = {func_val}

        # ——— Title ———
        title_cn = Text("分支切割: ", font_size=40, color=WHITE)
        title_math = Tex(f"$f(z) = {{{{func_str}}}}$", font_size=40, color=WHITE)
        title = VGroup(title_cn, title_math).arrange(RIGHT, buff=0.15)
        title.to_corner(UL)
        self.add_fixed_in_frame_mobjects(title)
        self.play(Write(title), run_time=1.5)

        # ——— Axes in 3D ———
        axes = ThreeDAxes(
            x_range=[-3, 3, 1],
            y_range=[-3, 3, 1],
            z_range=[-6, 6, 2],
            x_length=6,
            y_length=6,
            z_length=5,
        )
        x_label = axes.get_x_axis_label(Text("Re(z)", font_size=24))
        y_label = axes.get_y_axis_label(Text("Im(z)", font_size=24))
        z_label = axes.get_z_axis_label(Text("Im(Ln(z))", font_size=24))

        self.set_camera_orientation(phi=60 * DEGREES, theta=-45 * DEGREES)
        self.play(
            Create(axes), Write(x_label), Write(y_label), Write(z_label),
            run_time=2
        )

        # ——— Branch cut: dashed line along negative real axis ———
        branch_cut = DashedLine(
            axes.c2p(-3, 0, 0),
            axes.c2p(0, 0, 0),
            color=RED, stroke_width=4, dash_length=0.15
        )
        branch_label = Text("分支切割", font_size=24, color=RED)
        branch_label.next_to(branch_cut, DOWN, buff=0.3)
        branch_label.rotate_about_origin(-45 * DEGREES, axis=UP)
        self.play(Create(branch_cut), Write(branch_label), run_time=1.5)

        # ——— Riemann surface: spiral height as z orbits origin ———
        # Parametric curves showing the spiral nature of Ln(z)
        radii = [0.5, 1.0, 1.5, 2.0, 2.5]
        colors = [BLUE, TEAL, GREEN, YELLOW, ORANGE]
        spirals = VGroup()

        for r, color in zip(radii, colors):
            spiral = ParametricFunction(
                lambda t, r=r: axes.c2p(
                    r * np.cos(t),
                    r * np.sin(t),
                    t,  # height = arg(z) = Im(Ln(z))
                ),
                t_range=[-PI + 0.05, PI - 0.05, 0.05],
                color=color, stroke_width=2,
            )
            spirals.add(spiral)

        self.move_camera(phi=55 * DEGREES, theta=-55 * DEGREES, run_time=2)
        self.play(LaggedStart(*[Create(s) for s in spirals], lag_ratio=0.15), run_time=4)

        # ——— Animate a point orbiting, leaving a trail ———
        dot = Sphere(radius=0.08, color=WHITE).move_to(axes.c2p(1.5, 0, 0))
        trail = VMobject(color=WHITE, stroke_width=2)
        trail.set_points_as_corners([dot.get_center(), dot.get_center()])

        def update_trail(mob):
            mob.add_points_as_corners([dot.get_center()])

        trail.add_updater(update_trail)
        self.add(trail, dot)

        for angle in np.linspace(0, 4 * PI, 200):
            x = 1.5 * np.cos(angle)
            y = 1.5 * np.sin(angle)
            z = angle  # height = argument
            dot.move_to(axes.c2p(x, y, z))
            self.wait(0.01)

        trail.remove_updater(update_trail)
        self.wait(0.5)

        # ——— Conclusion ———
        conclusion = Text(
            "绕原点旋转一周 → 虚部升高 2π → 进入下一个黎曼面",
            font_size=22, color=YELLOW
        )
        conclusion.to_edge(DOWN, buff=0.3)
        self.add_fixed_in_frame_mobjects(conclusion)
        self.play(Write(conclusion), run_time=1.5)

        # Final rotation
        self.begin_ambient_camera_rotation(rate=0.15)
        self.wait(3)
        self.stop_ambient_camera_rotation()
'''
