"""Complex Plane Transform visualisation — four basic transformations."""

from app.animation.base import BaseManimTemplate


class ComplexPlaneTransformTemplate(BaseManimTemplate):
    template_name = "ComplexPlaneTransform"
    concept_ids = ["complex-7.1"]
    scene_class_name = "ComplexPlaneTransformScene"

    def validate(self, params: dict) -> bool:
        return bool(params.get("function"))

    def build_scene_code(self, params: dict) -> str:
        import json
        func_val = json.dumps(params.get("function", "z+1"))
        return f'''"""Complex Plane Transform animation — auto-generated by AnimationGenerator."""
import numpy as np
from manim import *

class {self.scene_class_name}(Scene):
    def construct(self):
        func_str = {func_val}

        # ——— Title ———
        title = Text("复平面基本变换", font_size=36, color=WHITE)
        title.to_edge(UP)
        self.play(Write(title), run_time=1.2)

        # ——— Four sub-panels ———
        transforms = [
            {{"name": "平移 z → z+a", "color": BLUE, "func": "z+1"}},
            {{"name": "旋转 z → e^iθ z", "color": GREEN, "func": "e^(i*PI/4)*z"}},
            {{"name": "缩放 z → kz", "color": ORANGE, "func": "2*z"}},
            {{"name": "反演 z → 1/z", "color": PURPLE, "func": "1/z"}},
        ]

        panels = []
        for i, t in enumerate(transforms[:4]):
            panel = Rectangle(width=3.5, height=4, color=t["color"], stroke_width=1.5, fill_opacity=0.05)
            panel.shift(LEFT * 5.5 + RIGHT * i * 3.7)
            panels.append(panel)

            mini = ComplexPlane(
                x_range=[-2, 2, 0.5], y_range=[-2, 2, 0.5],
                background_line_style={{"stroke_color": t["color"], "stroke_width": 0.3, "stroke_opacity": 0.2}},
            )
            mini.scale(0.4).move_to(panel.get_center())

            name_text = Text(t["name"], font_size=16, color=t["color"])
            name_text.next_to(panel, DOWN, buff=0.15)

            self.play(Create(panel), Create(mini), Write(name_text), run_time=1.2)

        # ——— Animate points ———
        dot_pairs = []
        for i, t in enumerate(transforms[:4]):
            pc = panels[i].get_center()
            orig_dot = Dot([pc[0]-0.5, pc[1]+0.3, 0], color=GREEN, radius=0.06)
            new_dot = Dot([pc[0]+0.3, pc[1]+0.3, 0], color=RED, radius=0.06)
            orig_label = MathTex("z", font_size=18, color=GREEN).next_to(orig_dot, DL, buff=0.1)
            new_label = MathTex("z'", font_size=18, color=RED).next_to(new_dot, DR, buff=0.1)
            dot_pairs.append((orig_dot, new_dot, orig_label, new_label))

        for orig_d, new_d, orig_l, new_l in dot_pairs:
            self.play(FadeIn(orig_d), FadeIn(new_d), Write(orig_l), Write(new_l), run_time=0.6)

        # ——— Arrows ———
        for orig_d, new_d, _, _ in dot_pairs:
            self.play(Create(Arrow(orig_d.get_center(), new_d.get_center(), color=YELLOW, buff=0.1)), run_time=0.4)

        # ——— Conclusion ———
        conclusion = Text(
            "共形映射研究复变函数如何变换复平面上的几何形状",
            font_size=22, color=YELLOW
        )
        conclusion.to_edge(DOWN, buff=0.5)
        self.play(Write(conclusion), run_time=1.5)
        self.wait(2)
'''
