"""Conformal Mapping visualisation — grid deformation under complex function."""

from app.animation.base import BaseManimTemplate


class ConformalMappingTemplate(BaseManimTemplate):
    template_name = "ConformalMapping"
    concept_ids = ["complex-7.1"]
    scene_class_name = "ConformalMappingScene"

    def validate(self, params: dict) -> bool:
        required = {"function"}
        if not required.issubset(params):
            return False
        if not params.get("function"):
            return False
        return True

    def build_scene_code(self, params: dict) -> str:
        import json
        params_json = json.dumps(params)
        return f'''"""Conformal Mapping animation — auto-generated by AnimationGenerator."""
import json, sys
from manim import *

class {self.scene_class_name}(Scene):
    def construct(self):
        params = json.loads(sys.argv[1])
        func_str = params.get("function", "z**2")
        domain_label = params.get("domain", "单位圆盘 |z|<1")

        # ——— Title ———
        title = Tex(
            f"共形映射: $f(z) = {func_str}$",
            font_size=40, color=WHITE
        )
        title.to_edge(UP)
        self.play(Write(title), run_time=1.5)

        # ——— Left: z-plane (domain) ———
        z_label = Tex("$z$-平面", font_size=28, color=BLUE)
        z_label.to_corner(UL).shift(DOWN * 0.5)
        z_plane = ComplexPlane(
            x_range=[-3, 3, 1], y_range=[-3, 3, 1],
            background_line_style={{"stroke_color": BLUE_C, "stroke_width": 0.8, "stroke_opacity": 0.4}},
        ).add_coordinates()
        z_plane.scale(0.55).shift(LEFT * 3.2)

        # Draw a grid of points in z-plane
        z_grid = VGroup()
        for x in [-2, -1, 0, 1, 2]:
            for y in [-2, -1, 0, 1, 2]:
                dot = Dot(z_plane.n2p(complex(x, y)), radius=0.04, color=BLUE)
                z_grid.add(dot)

        self.play(Create(z_plane), Write(z_label), run_time=1.5)
        self.play(LaggedStart(*[FadeIn(d) for d in z_grid], lag_ratio=0.02), run_time=1.5)
        self.wait(0.5)

        # ——— Right: w-plane (image) ———
        w_label = Tex("$w$-平面", font_size=28, color=GREEN)
        w_label.to_corner(UR).shift(DOWN * 0.5)
        w_plane = ComplexPlane(
            x_range=[-5, 5, 1], y_range=[-5, 5, 1],
            background_line_style={{"stroke_color": GREEN_C, "stroke_width": 0.8, "stroke_opacity": 0.4}},
        ).add_coordinates()
        w_plane.scale(0.55).shift(RIGHT * 3.2)
        self.play(Create(w_plane), Write(w_label), run_time=1.5)

        # ——— Animate the mapping ———
        # Each z point maps to f(z) in the w-plane
        self.play(AnimationGroup(*[
            dot.animate.move_to(w_plane.n2p(
                eval(func_str.replace("z", str(complex(x, y))))
            ))
            for dot, (x, y) in [
                (z_grid[i], (x, y))
                for i, (x, y) in enumerate(
                    [(x, y) for x in [-2, -1, 0, 1, 2] for y in [-2, -1, 0, 1, 2]]
                )
            ]
        ], lag_ratio=0.01), run_time=4)

        # ——— Result text ———
        result = Tex(
            f"$f$ 将 ${{{domain_label}}}$ 共形映射到 $w$-平面",
            font_size=28, color=WHITE
        )
        result.to_edge(DOWN, buff=0.6)
        self.play(Write(result), run_time=1.5)
        self.wait(1.5)
'''
