"""Contour Integration visualisation — parametric path with integrand."""

from app.animation.base import BaseManimTemplate


class ContourIntegrationTemplate(BaseManimTemplate):
    template_name = "ContourIntegration"
    concept_ids = ["complex-4.1", "complex-4.2", "complex-4.3"]
    scene_class_name = "ContourIntegrationScene"

    def validate(self, params: dict) -> bool:
        required = {"contour"}
        if not required.issubset(params):
            return False
        return True

    def build_scene_code(self, params: dict) -> str:
        import json
        contour_val = json.dumps(params.get("contour", "circle"))
        integrand_val = json.dumps(params.get("integrand", "f(z) = 1/z"))
        radius = float(params.get("radius", 2))
        return f'''"""Contour Integration animation — auto-generated by AnimationGenerator."""
import numpy as np
from manim import *

class {self.scene_class_name}(Scene):
    def construct(self):
        contour_type = {contour_val}
        integrand = {integrand_val}
        radius = {radius}

        # ——— Title ———
        title_cn = Text("围道积分: ", font_size=38, color=WHITE)
        title_math = Tex(f"$\\oint_C {{integrand}}\\,dz$", font_size=38, color=WHITE)
        title = VGroup(title_cn, title_math).arrange(RIGHT, buff=0.15)
        title.to_edge(UP)
        self.play(Write(title), run_time=1.5)

        # ——— Complex plane ———
        plane = ComplexPlane(
            x_range=[-4, 4, 1], y_range=[-4, 4, 1],
            background_line_style={{"stroke_color": BLUE_D, "stroke_width": 0.5, "stroke_opacity": 0.3}},
        ).add_coordinates()
        self.play(Create(plane), run_time=1.5)

        # ——— Draw contour ———
        if contour_type == "circle":
            contour = Circle(radius=radius, color=YELLOW, stroke_width=3)
        elif contour_type == "semicircle":
            contour = Arc(
                radius=radius, start_angle=0, angle=PI,
                color=YELLOW, stroke_width=3
            )
        else:
            contour = Circle(radius=radius, color=YELLOW, stroke_width=3)

        contour_label = MathTex(r"C", color=YELLOW, font_size=30)
        contour_label.next_to(contour, UP + RIGHT, buff=0.2)
        self.play(Create(contour), Write(contour_label), run_time=2)

        # ——— Moving point along contour ———
        dot = Dot(color=RED, radius=0.08)
        dot.move_to(contour.point_from_proportion(0))

        def update_dot(mob, alpha):
            mob.move_to(contour.point_from_proportion(alpha))

        self.play(
            UpdateFromAlphaFunc(dot, update_dot),
            run_time=4,
            rate_func=linear
        )
        self.wait(0.5)

        # ——— Direction arrow ———
        arrow = CurvedArrow(
            contour.point_from_proportion(0.2),
            contour.point_from_proportion(0.3),
            color=ORANGE, angle=-TAU/6
        )
        self.play(Create(arrow), run_time=1)

        # ——— Formula ———
        formula = MathTex(
            r"\\oint_C f(z)\\,dz",
            font_size=40, color=WHITE
        )
        formula.to_edge(DOWN, buff=0.8)
        self.play(Write(formula), run_time=1.5)
        self.wait(2)
'''
