"""C-R Equations visualisation — directional derivative comparison."""

from app.animation.base import BaseManimTemplate


class CREquationsTemplate(BaseManimTemplate):
    template_name = "CREquations"
    concept_ids = ["complex-2.2"]
    scene_class_name = "CREquationsScene"

    def validate(self, params: dict) -> bool:
        required = {"function"}
        return required.issubset(params) and bool(params.get("function"))

    def build_scene_code(self, params: dict) -> str:
        import json
        func_val = json.dumps(params.get("function", "z**2"))
        point_val = json.dumps(params.get("point", "1+i"))
        return f'''"""C-R Equations animation — auto-generated by AnimationGenerator."""
import numpy as np
from manim import *

class {self.scene_class_name}(ThreeDScene):
    def construct(self):
        func_str = {func_val}
        point_str = {point_val}

        title = Text("Cauchy-Riemann 方程可视化", font_size=36, color=WHITE)
        title.to_edge(UP)
        self.play(Write(title), run_time=1.5)

        plane = ComplexPlane(
            x_range=[-3, 3, 1], y_range=[-3, 3, 1],
            background_line_style={{"stroke_color": BLUE_D, "stroke_width": 0.5, "stroke_opacity": 0.3}},
        ).add_coordinates()
        plane.scale(0.7)
        self.play(Create(plane), run_time=1.5)

        try:
            z0 = complex(point_str.replace("i", "j"))
        except ValueError:
            z0 = complex(1, 1)
        point_dot = Dot(plane.n2p(z0), color=YELLOW, radius=0.08)
        point_label = MathTex("z_0", font_size=28, color=YELLOW)
        point_label.next_to(point_dot, UR, buff=0.15)
        self.play(FadeIn(point_dot), Write(point_label), run_time=1)

        # Approach along real axis
        x_dots = VGroup()
        for dx in np.linspace(0.5, 0.05, 12):
            dot = Dot(plane.n2p(z0 + complex(dx, 0)), radius=0.04, color=RED)
            x_dots.add(dot)
        x_label = Text("实轴方向逼近", font_size=24, color=RED)
        x_label.to_corner(DL, buff=0.5)
        self.play(LaggedStart(*[FadeIn(d) for d in x_dots], lag_ratio=0.05), Write(x_label), run_time=2)

        # Approach along imaginary axis
        y_dots = VGroup()
        for dy in np.linspace(0.5, 0.05, 12):
            dot = Dot(plane.n2p(z0 + complex(0, dy)), radius=0.04, color=GREEN)
            y_dots.add(dot)
        y_label = Text("虚轴方向逼近", font_size=24, color=GREEN)
        y_label.next_to(x_label, RIGHT, buff=0.3)
        self.play(LaggedStart(*[FadeIn(d) for d in y_dots], lag_ratio=0.05), Write(y_label), run_time=2)

        # C-R formula
        cr_formula = MathTex(
            r"{{\\partial u \\over \\partial x}} = {{\\partial v \\over \\partial y}},\\quad " +
            r"{{\\partial u \\over \\partial y}} = -{{\\partial v \\over \\partial x}}",
            font_size=32, color=WHITE
        )
        cr_formula.to_edge(DOWN, buff=0.6)
        box = SurroundingRectangle(cr_formula, color=YELLOW, buff=0.2)
        self.play(Write(cr_formula), Create(box), run_time=2.5)

        conclusion = Text(
            "解析函数 → 导数与方向无关 → C-R 条件是必要且充分的",
            font_size=24, color=YELLOW
        )
        conclusion.next_to(cr_formula, UP, buff=0.4)
        self.play(Write(conclusion), run_time=2)
        self.wait(2)
'''
