"""Laurent Series visualisation — positive + negative powers in annulus."""

from app.animation.base import BaseManimTemplate


class LaurentSeriesTemplate(BaseManimTemplate):
    template_name = "LaurentSeries"
    concept_ids = ["complex-5.2"]
    scene_class_name = "LaurentSeriesScene"

    def validate(self, params: dict) -> bool:
        return bool(params.get("function"))

    def build_scene_code(self, params: dict) -> str:
        import json
        func_val = json.dumps(params.get("function", "1/(z*(z-1))"))
        inner_r = float(params.get("inner_radius", 0.5))
        outer_r = float(params.get("outer_radius", 2.0))
        return f'''"""Laurent Series animation — auto-generated by AnimationGenerator."""
from manim import *

class {self.scene_class_name}(Scene):
    def construct(self):
        func_str = {func_val}
        r1 = {inner_r}
        r2 = {outer_r}

        # ——— Title ———
        title_cn = Text("洛朗级数: ", font_size=36, color=WHITE)
        title_math = Tex(f"$f(z) = {{func_str}}$", font_size=36, color=WHITE)
        title = VGroup(title_cn, title_math).arrange(RIGHT, buff=0.15)
        title.to_edge(UP)
        self.play(Write(title), run_time=1.5)

        plane = ComplexPlane(
            x_range=[-3, 3, 1], y_range=[-3, 3, 1],
            background_line_style={{"stroke_color": BLUE_D, "stroke_width": 0.5, "stroke_opacity": 0.3}},
        ).add_coordinates()
        plane.scale(0.7)
        self.play(Create(plane), run_time=1.5)

        # Inner circle
        inner = Circle(radius=r1, color=RED, stroke_width=2)
        inner.move_to(plane.n2p(complex(0, 0)))
        inner_label = Text("内圆", font_size=22, color=RED)
        inner_label.next_to(inner, DOWN, buff=0.15)

        # Outer circle
        outer = Circle(radius=r2, color=GREEN, stroke_width=2)
        outer.move_to(plane.n2p(complex(0, 0)))
        outer_label = Text("外圆", font_size=22, color=GREEN)
        outer_label.next_to(outer, UP, buff=0.15)

        self.play(Create(inner), Create(outer), Write(inner_label), Write(outer_label), run_time=2)

        # Annulus shading
        annulus = Annulus(inner_radius=r1, outer_radius=r2, color=YELLOW, fill_opacity=0.15)
        annulus.move_to(plane.n2p(complex(0, 0)))
        self.play(FadeIn(annulus), run_time=1.5)

        # Laurent formula
        formula = MathTex(
            r"f(z) = \\sum_{{n=-\\infty}}^{{\\infty}} a_n (z - z_0)^n",
            font_size=32, color=WHITE
        )
        formula.to_edge(DOWN, buff=0.6)

        pos_text = Text("正幂项 (n≥0): 从内向外展开", font_size=22, color=GREEN)
        pos_text.next_to(formula, UP, buff=0.5)
        neg_text = Text("负幂项 (n<0): 从外向内展开", font_size=22, color=RED)
        neg_text.next_to(pos_text, DOWN, buff=0.1)

        self.play(Write(formula), run_time=2)
        self.play(Write(pos_text), Write(neg_text), run_time=1.5)
        self.wait(2)
'''
