"""Pole Classification visualisation — three singularity types side-by-side."""

from app.animation.base import BaseManimTemplate


class PoleClassificationTemplate(BaseManimTemplate):
    template_name = "PoleClassification"
    concept_ids = ["complex-6.1"]
    scene_class_name = "PoleClassificationScene"

    def validate(self, params: dict) -> bool:
        return isinstance(params.get("singularities"), list)

    def build_scene_code(self, params: dict) -> str:
        import json
        singularities_val = json.dumps(params.get("singularities", [
            {"type": "removable", "point": "0", "label": "可去奇点: sin(z)/z"},
            {"type": "pole", "point": "0", "label": "极点: 1/z"},
            {"type": "essential", "point": "0", "label": "本性奇点: exp(1/z)"},
        ]))
        return f'''"""Pole Classification animation — auto-generated by AnimationGenerator."""
import numpy as np
from manim import *

class {self.scene_class_name}(Scene):
    def construct(self):
        singularities = {singularities_val}

        title = Text("孤立奇点分类", font_size=36, color=WHITE)
        title.to_edge(UP)
        self.play(Write(title), run_time=1.2)

        panels = []
        colors = [BLUE, RED, PURPLE]
        for i, sing in enumerate(singularities[:3]):
            panel = Rectangle(width=4, height=5, color=colors[i], stroke_width=2, fill_opacity=0.05)
            panel.shift(LEFT * 4 + RIGHT * i * 4)
            panels.append(panel)

            mini_plane = ComplexPlane(
                x_range=[-1.5, 1.5, 0.5], y_range=[-1.5, 1.5, 0.5],
                background_line_style={{"stroke_color": colors[i], "stroke_width": 0.3, "stroke_opacity": 0.2}},
            )
            mini_plane.scale(0.45).move_to(panel.get_center())

            type_text = Text(sing.get("label", ""), font_size=20, color=colors[i])
            type_text.next_to(panel, DOWN, buff=0.2)

            self.play(Create(panel), Create(mini_plane), Write(type_text), run_time=1.5)

        type_names = [
            Text("极限存在", font_size=22, color=GREEN).next_to(panels[0], UP, buff=0.3),
            Text("|f| → ∞", font_size=22, color=ORANGE).next_to(panels[1], UP, buff=0.3),
            Text("震荡/稠密", font_size=22, color=PURPLE).next_to(panels[2], UP, buff=0.3),
        ]
        for tn in type_names:
            self.play(Write(tn), run_time=0.8)
        self.wait(2)
'''
