"""Residue Theorem visualisation — contour with poles inside/outside."""

from app.animation.base import BaseManimTemplate


class ResidueTheoremTemplate(BaseManimTemplate):
    template_name = "ResidueTheorem"
    concept_ids = ["complex-6.1", "complex-6.2", "complex-6.3"]
    scene_class_name = "ResidueTheoremScene"

    def validate(self, params: dict) -> bool:
        required = {"poles", "inside_poles"}
        if not required.issubset(params):
            return False
        if not isinstance(params.get("poles"), list) or len(params["poles"]) < 1:
            return False
        return True

    def build_scene_code(self, params: dict) -> str:
        import json
        poles_val = json.dumps(params.get("poles", ["i", "-i"]))
        inside_val = json.dumps(params.get("inside_poles", ["i"]))
        radius = json.dumps(params.get("contour_radius", 2.0))
        return f'''"""Residue Theorem animation — auto-generated by AnimationGenerator."""
from manim import *

class {self.scene_class_name}(ThreeDScene):
    def construct(self):
        poles = {poles_val}
        inside_poles = {inside_val}
        contour_radius = {radius}

        # ——— Step 1: draw the complex plane ———
        plane = ComplexPlane(
            x_range=[-4, 4, 1], y_range=[-4, 4, 1],
            background_line_style={{"stroke_color": BLUE_D, "stroke_width": 0.5, "stroke_opacity": 0.3}},
        ).add_coordinates()
        self.play(Create(plane), run_time=1.5)
        self.wait(0.3)

        # ——— Step 2: draw the contour ———
        contour = Circle(radius=contour_radius, color=YELLOW, stroke_width=3)
        contour_label = MathTex(r"\\oint_C f(z)\\,dz", color=YELLOW)
        contour_label.next_to(contour, UP, buff=0.3)
        self.play(Create(contour), Write(contour_label), run_time=2)
        self.wait(0.5)

        # ——— Step 3: place poles ———
        dot_objects = []
        for i, pole_str in enumerate(poles):
            try:
                z = complex(pole_str.replace("i", "j"))
            except ValueError:
                z = complex(i, 0)
            dot = Dot(plane.n2p(z), color=RED, radius=0.1)
            label = MathTex(f"z_{{i+1}}={{pole_str}}", font_size=28, color=RED)
            label.next_to(dot, UP + RIGHT, buff=0.15)
            dot_objects.append((dot, label, z, pole_str in inside_poles))

        for dot, label, _, _ in dot_objects:
            self.play(FadeIn(dot), Write(label), run_time=0.5)

        # ——— Step 4: highlight poles inside vs outside ———
        inside_group = VGroup()
        outside_group = VGroup()
        for dot, label, z, is_inside in dot_objects:
            if is_inside:
                inside_group.add(dot, label)
                dot.set_color(GREEN)
                label.set_color(GREEN)
            else:
                outside_group.add(dot, label)
                dot.set_color(GRAY)
                label.set_color(GRAY)

        self.wait(0.5)

        # ——— Step 5: formula ———
        formula = MathTex(
            r"\\oint_C f(z)\\,dz = 2\\pi i \\sum \\operatorname{{Res}}[f, z_k]",
            font_size=36, color=WHITE
        )
        formula.to_edge(DOWN, buff=0.8)
        box = SurroundingRectangle(formula, color=GREEN, buff=0.2)
        self.play(Write(formula), Create(box), run_time=2.5)
        self.wait(1.5)

        # ——— Step 6: fade to black ———
        self.play(*[FadeOut(m) for m in self.mobjects], run_time=1)
'''
