"""Riemann Sphere visualisation — stereographic projection from plane to sphere."""

from app.animation.base import BaseManimTemplate


class RiemannSphereTemplate(BaseManimTemplate):
    template_name = "RiemannSphere"
    concept_ids = ["complex-1.2"]
    scene_class_name = "RiemannSphereScene"

    def validate(self, params: dict) -> bool:
        return bool(params.get("function"))

    def build_scene_code(self, params: dict) -> str:
        import json
        func_val = json.dumps(params.get("function", "z"))
        return f'''"""Riemann Sphere animation — auto-generated by AnimationGenerator."""
import numpy as np
from manim import *

class {self.scene_class_name}(ThreeDScene):
    def construct(self):
        func_str = {func_val}

        # ——— Title ———
        title = VGroup(
            Text("黎曼球面: ", font_size=34, color=WHITE),
            Tex(f"$f(z) = {{func_str}}$", font_size=34, color=WHITE),
        ).arrange(RIGHT, buff=0.15)
        title.to_edge(UP)
        self.add_fixed_in_frame_mobjects(title)
        self.play(Write(title), run_time=1.2)

        # ——— Sphere ———
        sphere = Sphere(radius=1.5, resolution=(24, 24))
        sphere.set_fill(BLUE_E, opacity=0.15)
        sphere.set_stroke(BLUE_D, 1.5)
        self.play(Create(sphere), run_time=2)

        # ——— North pole marker (infinity) ———
        north = Dot([0, 0, 1.5], radius=0.08, color=GOLD)
        north_label = Text("∞", font_size=28, color=GOLD)
        north_label.next_to(north, UP, buff=0.2)
        self.add_fixed_orientation_mobjects(north_label)

        # ——— South pole marker (origin) ———
        south = Dot([0, 0, -1.5], radius=0.08, color=GREEN)
        south_label = MathTex("z=0", font_size=22, color=GREEN)
        south_label.next_to(south, DOWN, buff=0.2)
        self.add_fixed_orientation_mobjects(south_label)

        self.play(FadeIn(north), Write(north_label), FadeIn(south), Write(south_label), run_time=1.5)

        # ——— Complex plane (at equator, horizontal) ———
        plane = Circle(radius=1.8, color=BLUE_C, stroke_width=1, fill_opacity=0.05)
        plane.rotate(PI/2, axis=RIGHT)
        self.play(Create(plane), run_time=1.5)

        # ——— Grid points on plane ———
        grid_dots = VGroup()
        for x in np.linspace(-1.5, 1.5, 7):
            for y in np.linspace(-1.5, 1.5, 7):
                if abs(complex(x, y)) <= 1.5:
                    dot = Dot3D([x, y, 0], radius=0.03, color=BLUE)
                    grid_dots.add(dot)
        self.play(LaggedStart(*[FadeIn(d) for d in grid_dots], lag_ratio=0.01), run_time=1.5)

        # ——— Project lines: plane points → sphere ———
        lines = VGroup()
        for dot in grid_dots[:20]:
            p = dot.get_center()
            line = DashedLine(p, [0, 0, 1.5], color=YELLOW, stroke_width=0.5, dash_length=0.08)
            lines.add(line)
        self.play(LaggedStart(*[Create(l) for l in lines], lag_ratio=0.02), run_time=2)

        # ——— Conclusion ———
        conclusion = Text(
            "球极投影: 复平面上的每一点唯一对应球面上的一点\\n北极 = 无穷远点 ∞",
            font_size=22, color=YELLOW
        )
        conclusion.to_edge(DOWN, buff=0.3)
        self.add_fixed_in_frame_mobjects(conclusion)
        self.play(Write(conclusion), run_time=2)

        # ——— Camera rotate ———
        self.move_camera(phi=60 * DEGREES, theta=-30 * DEGREES, run_time=3)
        self.wait(1.5)
'''
