"""Taylor Series visualisation — partial sums approaching function."""

from app.animation.base import BaseManimTemplate


class TaylorSeriesTemplate(BaseManimTemplate):
    template_name = "TaylorSeries"
    concept_ids = ["complex-5.1"]
    scene_class_name = "TaylorSeriesScene"

    def validate(self, params: dict) -> bool:
        return bool(params.get("function"))

    def build_scene_code(self, params: dict) -> str:
        import json
        func_val = json.dumps(params.get("function", "exp(z)"))
        terms = int(params.get("terms", 5))
        return f'''"""Taylor Series animation — auto-generated by AnimationGenerator."""
import numpy as np
from manim import *

class {self.scene_class_name}(Scene):
    def construct(self):
        func_str = {func_val}
        max_terms = {terms}

        # ——— Title ———
        title_cn = Text("泰勒级数逼近: ", font_size=36, color=WHITE)
        title_math = Tex(f"$f(z) = {{func_str}}$", font_size=36, color=WHITE)
        title = VGroup(title_cn, title_math).arrange(RIGHT, buff=0.15)
        title.to_edge(UP)
        self.play(Write(title), run_time=1.2)

        plane = ComplexPlane(
            x_range=[-3, 3, 1], y_range=[-3, 3, 1],
            background_line_style={{"stroke_color": BLUE_D, "stroke_width": 0.5, "stroke_opacity": 0.3}},
        ).add_coordinates()
        plane.scale(0.7)
        self.play(Create(plane), run_time=1.5)

        # Convergence circle
        conv_circle = Circle(radius=2.0, color=YELLOW, stroke_width=2)
        conv_circle.move_to(plane.n2p(complex(0, 0)))
        conv_label = Text("收敛圆", font_size=22, color=YELLOW)
        conv_label.next_to(conv_circle, UP, buff=0.15)
        self.play(Create(conv_circle), Write(conv_label), run_time=1.5)

        # Terms display
        term_labels = VGroup()
        for n in range(max_terms):
            label = Text(
                "T" + str(n+1) + ": z^" + str(n+1) + "/" + str(n+1),
                font_size=20, color=WHITE
            )
            label.scale(0.7)
            label.to_corner(UR, buff=0.3).shift(DOWN * n * 0.4)
            term_labels.add(label)

        self.play(LaggedStart(*[Write(t) for t in term_labels], lag_ratio=0.2), run_time=2)

        # Sequential approximation
        for n in range(1, min(max_terms, 6)):
            dot = Dot(plane.n2p(complex(0.5 + 1.2, 0)), color=GREEN, radius=0.06)
            n_text = Text("T_" + str(n), font_size=22, color=GREEN)
            n_text.next_to(dot, RIGHT, buff=0.3)
            self.play(FadeIn(dot), Write(n_text), run_time=0.5)
            self.remove(dot, n_text)

        conclusion = Text("逐项叠加 → 在收敛圆内逼近解析函数", font_size=24, color=YELLOW)
        conclusion.to_edge(DOWN, buff=0.6)
        self.play(Write(conclusion), run_time=1.5)
        self.wait(2)
'''
